default_install_hook_types: [pre-commit, commit-msg, pre-push]
default_language_version:
    python: python3.11

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7
    hooks:
      - id: ruff-check
        types_or: [ python, pyi, jupyter, pyproject ]
        args: [ --fix ]
        stages: [ pre-commit ]
      - id: ruff-format
        stages: [ pre-commit ]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args: [ --py311-plus ]
        stages: [ pre-commit ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        stages: [ pre-commit ]
      - id: end-of-file-fixer
        stages: [ pre-commit ]
      - id: check-yaml
        args: [ --unsafe ]
        stages: [ pre-commit ]
      - id: check-toml
        stages: [ pre-commit ]
      - id: fix-byte-order-marker
        stages: [ pre-commit ]
      - id: name-tests-test
        args: [ --pytest-test-first ]
        stages: [ pre-commit ]
